Version update 1.2

diff --git a/scripts/sdwdate b/scripts/sdwdate
--- a/scripts/sdwdate
+++ b/scripts/sdwdate
@@ -1,13 +1,14 @@
 #!/usr/bin/zsh
 
-# This is a Cobalt-specific simplistic reimplementation of Kicksecure's sdwdate, in the form of a shell script.
+# This is a simplistic reimplementation of Kicksecure's sdwdate, in the form of a shell script.
 # Cobalt sdwdate will randomly select 3 websites to fetch the date from over Tor, and set the system clock to the average of all three dates.
 # Unlike regular sdwdate, this script runs over Tor, but connects to clearnet websites.
 
 # TODO: use curl over tor, choose several servers randomly from sdwdate.servers
 
 CURL_DATE=($(curl -v "https://gnu.org" 2>&1 | tr '[:upper:]' '[:lower:]' | grep "< date")) # tr ... is to ensure that the date field is always lowercase (it sometimes isn't)
-case ${CURL_DATE[4]} in
+
+case ${CURL_DATE[5]} in
 	jan) MONTH=01;;
 	feb) MONTH=02;;
 	mar) MONTH=03;;
@@ -20,7 +21,12 @@ case ${CURL_DATE[4]} in
 	oct) MONTH=10;;
 	nov) MONTH=11;;
 	dec) MONTH=12;;
+	*)
+		echo "Date parsing error"
+		exit 1
+		;;
 esac
-CURL_DATE="${CURL_DATE[5]}-$MONTH-${CURL_DATE[3]} ${CURL_DATE[6]}"
+
+CURL_DATE="${CURL_DATE[6]}-$MONTH-${CURL_DATE[4]} ${CURL_DATE[7]}"
 
 date -u -s "$CURL_DATE"
